server:
  port: ${PORT:8080}
  servlet:
    context-path: /producer-api
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024

spring:
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
  servlet:
    encoding:
      charset: UTF-8
      force: true

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION}